### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by suve** [dos1/libsuperderpy#1]
When a game fails to load a gamestate, the error message is often too long to fit the screen.
It would be nice if the message employed some kind of text wrapping. 

Preferably, on Linux, it could also dump the error message to console (either on `stderr` or `stdout`).

**Comment by suve** [comment]
An example:
![screenshot from 2017-11-27 19-03-25](https://user-images.githubusercontent.com/5345765/33281605-207d1f8a-d3a6-11e7-8d46-cd22e6f70ab6.png)

**Comment by dos1** [comment]
Sorry for long wait! Thanks a lot for the PR #2. You have become the first libsuperderpy contributor, congratulations! :)

I've merged it. Also, good idea with stderr - added it as well.

In case you would want to make some other PRs, check out the README_codestyle.md file - clang-tidy and clang-format are a neat little tools to automatically ensure that the code is somewhat consistent with its surroundings :)

**Comment by dos1** [comment]
BTW. Just so you know, there's _DrawWrappedText_ function in the library already, but the height between lines is not configurable, so for now I opted for visual consistency and left your code intact. I'll think what to do with it later.

Also, there's a config file (under GNU/Linux it's usually ~/.config/dosowisko.net/_GameName_/SuperDerpy.ini) where, along some other options, you can enable debug mode, which, when enabled, prints all console messages to stdout.
```
[SuperDerpy]
debug=1
```
I should really document it somewhere someday :)
